### ISSUE TITLE
[BUG] Hold other Lever for Stepwise Up/Down

### ISSUE THREAD

**Issue by n3roGit** [n3roGit/DPVControl#11]
| Switch 1 | Switch 2 | Function |
|:--------:|:--------:|:--------:|
| 2 Clicks | Hold     | Stepwise slower |
| Hold     | 2 Clicks | Stepwise faster |

Please adjust the code so that one side must always be held to change the speed. currently this is not necessary to hold.

**Comment by happyherp** [comment]
See 7f8cd3af7657b445089ed14b603a24b0f25b2423 
With this change the speed change will only happen, if the other lever is also pressed **at the time that the other lever is released on the second click**. So you technically do not need to hold the other lever all the time, just at the very end. Implementing it in a way that the other button needs to be hold down the whole time takes more work.

**Comment by n3roGit** [comment]
Perfect! Working!

**Comment by n3roGit** [comment]
sorry for close
