### ISSUE TITLE
[FEATURE] Emergency stop - PRIO 2

### ISSUE THREAD

**Issue by n3roGit** [n3roGit/DPVControl#19]
We need to monitor the value for getVescUart().data.rpm while the motor is running. If it is not approaching the desired speed as expected or if it suddenly stops, we assume that something has jammed. the motor must then be stopped immediately.

You could also use getVescUart().data.avgInputCurrent, as a strong fluctuation in the current consumption could also be an indication.

**Comment by happyherp** [comment]
I put this in the motor_by_rpm branch. 
36f21eea86435f680d1b420bdd84f893a5a3935c

**Comment by n3roGit** [comment]
https://github.com/n3roGit/DPVControl/issues/37

**Comment by n3roGit** [comment]
> I put this in the motor_by_rpm branch. 
> 36f21eea86435f680d1b420bdd84f893a5a3935c
> 

Whats happening when motor is jammed on startup? In this case ampere rises and we have no RPM

**Comment by n3roGit** [comment]
.
