### ISSUE TITLE
Move away from arduino IDE - PRIO ?

### ISSUE THREAD

**Issue by happyherp** [n3roGit/DPVControl#26]
I dont like the IDE of Arduino that much. It was nice to get started, but i think there are better tools out there. 

I don't like the .ino files. It makes me create to many global variables. 
Also sometimes the arduino compiler seems to move declarations around that cause strange bugs.

**Comment by happyherp** [comment]
I see there already is a branch https://github.com/n3roGit/DPVControl/tree/test-visual-studio-code

i am looking at this tutorial...
https://colddsam.medium.com/exploring-the-world-of-arduino-programming-in-visual-studio-code-bbcb4af982e7

**Comment by happyherp** [comment]
What seems to work ok-ish.
VSCode with Arduido plugin from microsoft.
then install gcc compiler. https://nuwen.net/mingw.html
select the compiler in vscode.
then install the libraries that we use from inside vscode using the arduino library manager. If some are missing they need to be put in C:\Users\<user>\Documents\Arduino\libraries so that they can be found there. 

with that I can currently run verify and also upload to the board.
But there are MANY compilation errors. Most probably because of the .ino files. To fix this we would need to make them all .h/.cpp

**Comment by n3roGit** [comment]
Yes, I also had these errors. I think it is due to the INO files. that is simply not intended for VSC.

**Comment by happyherp** [comment]
i converted almost all code to cpp. 

Still my configuration shows wrong errors: 
![image](https://github.com/n3roGit/DPVControl/assets/2945814/9f0844ac-55ac-49be-b15e-6e6ec9dfaefb)

**Comment by n3roGit** [comment]
I think he is missing some default librarys. I search for this problem

**Comment by n3roGit** [comment]
![image](https://github.com/n3roGit/DPVControl/assets/8565847/2c2050a7-73fd-4508-b648-b6d0025f305c)
![image](https://github.com/n3roGit/DPVControl/assets/8565847/65cbacdf-ce37-48ff-bd02-9df5c048c2d2)


i got only this message with vscode branch

**Comment by n3roGit** [comment]
check this https://github.com/n3roGit/DPVControl/commit/f5c7687e6f8adc7d1396db4811dcc097611e2076
![image](https://github.com/n3roGit/DPVControl/assets/8565847/033799e2-9f41-4723-aa23-b6cbce74f2e4)

with this its building bot not 100%
![image](https://github.com/n3roGit/DPVControl/assets/8565847/4accd13e-ea32-458b-b096-bc7a7a8254f1)

ö

**Comment by n3roGit** [comment]
HA, Now its working!!!!!!!!


I can flash!

**Comment by n3roGit** [comment]
Ah you need one thing:
https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.msi
![image](https://github.com/n3roGit/DPVControl/assets/8565847/56799160-cc48-4431-90f9-41b4b9ef33e1)
![image](https://github.com/n3roGit/DPVControl/assets/8565847/5764bb6d-049c-42e4-ac43-f54f4703f500)
And set the CLI as compiler
C:\Program Files\Arduino CLI\

**Comment by n3roGit** [comment]
After the changeover, communication with the vesc no longer works. we should take another look at this.

**Comment by n3roGit** [comment]
tried:
`  if (getVescUart().getVescValues()) {
    Serial.println("Connected to VESC.");
  } else {
    Serial.println("Failed to connect to VESC.");
    hasMotor = true;
  }`
  
  
  and got this;
  
  
  ` Failed to get VESC data!: 0
 Failed to get VESC data!: 0`

**Comment by n3roGit** [comment]
https://github.com/microsoft/vscode-arduino


i try it like this. working on it

**Comment by n3roGit** [comment]
https://github.com/microsoft/vscode-arduino/blob/374c78f8ed06c1e88df480b687c24c06b728e13b/README.md?plain=1#L39


`- The supported legacy Arduino IDE versions are `1.6.x` and up to, but not including, `2.0.0`.
- The Windows Store's version of the Arduino IDE is not supported because of the sandbox environment that the application runs in.
- *Note:* Arduino IDE `1.8.7` had some breaking changes, causing board package and library installation failures.  These failures were corrected in `1.8.8` and later.
- *Note:* Arduino IDE `2.X.Y` is not supported and there are no plans for support in the future ([issue 1477](https://github.com/microsoft/vscode-arduino/issues/1477)).
`

**Comment by happyherp** [comment]
![image](https://github.com/n3roGit/DPVControl/assets/2945814/886dab57-6844-40d1-9037-9d19e0357b7b)
That sums up the situation. Files are there, and vscode seems to know where. But CodeAnalysis does not find them.

**Comment by happyherp** [comment]
> tried: ` if (getVescUart().getVescValues()) { Serial.println("Connected to VESC."); } else { Serial.println("Failed to connect to VESC."); hasMotor = true; }`
> 
> and got this;
> 
> ` Failed to get VESC data!: 0 Failed to get VESC data!: 0`

That is coming from somewhere else. 
See the other.cpp

```
void GetVESCValues() {

  if (!hasMotor) return;

  if (getVescUart().getVescValues()) {
    /*
    Serial.print("RPM: ");
    Serial.println(UART.data.rpm);
    Serial.print("inpVoltage: ");
    Serial.println(UART.data.inpVoltage);
    Serial.print("ampHours: ");
    Serial.println(UART.data.ampHours);
    Serial.print("tachometerAbs: ");
    Serial.println(UART.data.tachometerAbs);
    */

    updateBatteryLevel(getVescUart().data.inpVoltage);
  } else {
    log("Failed to get VESC data!", 00000);
  }
}
```

**Comment by n3roGit** [comment]
> ![image](https://github.com/n3roGit/DPVControl/assets/2945814/886dab57-6844-40d1-9037-9d19e0357b7b)
> That sums up the situation. Files are there, and vscode seems to know where. But CodeAnalysis does not find them. 

Maybe need to disable this feature?

**Comment by happyherp** [comment]
I will disable it. I wanted to have the static c++ code analysis. But it is still better than Arduino IDE. I will merge what we have to prod and move on.
