### ISSUE TITLE
[BUG] Cruise Control - PRIO 1

### ISSUE THREAD

**Issue by n3roGit** [n3roGit/DPVControl#27]
I have just noticed the following.
When I activate CruiseControl and let the engine run, it goes into standby after 60 seconds and stops the engine.

`currentMotorSpeed: 0.90
currentMotorSpeed: 0.91
currentMotorSpeed: 0.92
currentMotorSpeed: 0.94
currentMotorSpeed: 0.95
currentMotorSpeed: 0.96
currentMotorSpeed: 0.97
currentMotorSpeed: 0.98
currentMotorSpeed: 1.00
 going to standby: 100430010
beepSequence:2
targetMotorSpeed: 0.00
currentMotorSpeed: 0.97
`

**Comment by happyherp** [comment]
try 3f463a4c3c4d469624d3ed844a42e7e67d535e06
