### ISSUE TITLE
[BUG] double beep when going to standby - PRIO 3

### ISSUE THREAD

**Issue by n3roGit** [n3roGit/DPVControl#29]
i have noticed that i get two beeps when the device goes into standby. 

Beep for going to standby and for still on standby = 21
 
 
```
 going to standby: 203259027
beepSequence:2
beepSequence:1
 still in standby: 1
```

**Comment by happyherp** [comment]
try this d942c9b6cf0ce58863c2b21d5877d8881adbc3fd
